version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    container_name: nginx
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client

  server:
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
