version: '3'
services:
  nginx:
    image: nginx
    ports: -80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: -4000:4000
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: -80:80
    restart: always
