version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
